services:
  kafka:
    image: confluentinc/confluent-local:7.6.2
    hostname: kafka-sr-compat
    container_name: kafka-sr-compat
    networks:
      - sr-compat-net
    ports:
      - "9092:9092"
      - "19092:19092"
      - "39092:39092"
      - "49092:49092"
      - "59092:59092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,SASL_DOCKER:SASL_PLAINTEXT,PLAIN_HOST:PLAINTEXT,PLAIN_HOST_DOCKER:PLAINTEXT,SASL_HOST:SASL_PLAINTEXT
      KAFKA_LISTENERS: BROKER://:9092, CONTROLLER://:9093,PLAIN_HOST://:39092,PLAIN_HOST_DOCKER://:49092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-assignmentupdates:9092,PLAIN_HOST://localhost:39092,PLAIN_HOST_DOCKER://host.docker.internal:49092
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf"

  sr:
    image: confluentinc/cp-schema-registry:7.6.2
    hostname: sr
    container_name: sr-compat
    networks:
      - sr-compat-net
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: sr
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: "schemas"
      # SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFIED_ALGORITHM: "https"
      SCHEMA_REGISTRY_KAFKASTORE_REQUEST_TIMEOUT_MS: 20000
      SCHEMA_REGISTRY_KAFKASTORE_RETRY_BACKOFF_MS: 500
      #SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "SASL_SSL"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: host.docker.internal:49092
      #SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"alice\" password=\"alice-secret\";"
      #SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: "PLAIN"
      SCHEMA_REGISTRY_CONFLUENT_LICENSE_REPLICATION_FACTOR: 3
      # SCHEMA_REGISTRY_CONFLUENT_LICENSE: $CONFLUENT_LICENSE

networks:
  sr-compat-net: